export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const GET_PROVDERS_REQUEST_STARTED = 'GET_PROVDERS_REQUEST_STARTED';
export const GET_PROVDERS_REQUEST_SUCCESS = 'GET_PROVDERS_REQUEST_SUCCESS';
export const GET_PROVDERS_REQUEST_FAILED = 'GET_PROVDERS_REQUEST_FAILED';

export const ADD_PROVIDER = 'ADD_PROVIDER';
export const REMOVE_PROVIDER = 'REMOVE_PROVIDER';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
