export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const GET_PROVIDERS_REQUEST_STARTED = 'GET_PROVIDERS_REQUEST_STARTED';
export const GET_PROVIDERS_REQUEST_SUCCESS = 'GET_PROVIDERS_REQUEST_SUCCESS';
export const GET_PROVIDERS_REQUEST_FAILED = 'GET_PROVIDERS_REQUEST_FAILED';

export const ADD_PROVIDER = 'ADD_PROVIDER';
export const REMOVE_PROVIDER = 'REMOVE_PROVIDER';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';

export const GET_PROVIDER_NEWS_REQUEST_STARTED =
  'GET_PROVIDER_NEWS_REQUEST_STARTED';
export const GET_PROVIDER_NEWS_REQUEST_SUCCESS =
  'GET_PROVIDER_NEWS_REQUEST_SUCCESS';
export const GET_PROVIDER_NEWS_REQUEST_FAILED =
  'GET_PROVIDER_NEWS_REQUEST_FAILED';
