export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const GET_PROVDERS_REQUEST_STARTED = 'GET_PROVDERS_REQUEST_STARTED';
export const GET_PROVDERS_REQUEST_SUCCESS = 'GET_PROVDERS_REQUEST_SUCCESS';
export const GET_PROVDERS_REQUEST_FAILED = 'GET_PROVDERS_REQUEST_FAILED';
