import { TDic } from '@types';

const STR: TDic = {
  addBookmark: 'Add bookmark',
  animation: 'Animation',
  bookmarks: 'Bookmarks',
  category: {
    business: 'Business',
    it: 'IT',
    military: 'Military',
    news: 'News',
    technology: 'Technology',
    science: 'Science',
    softwareDevelopment: 'IT',
    space: 'Space',
  },
  changeLanguage: 'Change language',
  changeTheme: 'Change theme',
  genericError: 'Something went wrong. Try again later.',
  hideProvider: 'Hide provider',
  home: 'Home',
  language: 'Language',
  languages: {
    en: 'English',
    ua: 'Ukrainian',
  },
  loading: 'L O A D I N G ...',
  loadMore: 'Load more',
  noBookmarks: 'No bookmarks',
  noNews: 'No news',
  noProviders: 'No providers added. Add some from the Providers page.',
  providers: 'Providers',
  refresh: 'Refresh',
  removeBookmark: 'Remove bookmark',
  settings: 'Settings',
  share: 'Share',
  showProvider: 'Show provider',
  thumbnail: 'Thumbnail',
  theme: 'Theme',
  themes: {
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    'dark-blue': 'Dark Blue',
    'dark-red': 'Dark Red',
  },
  today: 'Today',
  yesterday: 'Yesterday',
};

export default STR;
