import { TDic } from 'types';

const STR: TDic = {
  home: 'Головна',
  changeLanguage: 'Змінити мову',
  changeTheme: 'Змінити тему',
  refresh: 'Оновити',
  loadMore: 'Завантажити ще',
  loading: 'З А В А Н Т А Ж Е Н Н Я ...',
  providers: 'Провайдери',
  showProvider: 'Показати провайдера',
  noProviders: 'Немає провайдерів. Виберіть декілька на сторінці «Провайдери».',
  hideProvider: 'Приховати провайдера',
  bookmarks: 'Закладки',
  addBookmark: 'Додати закладку',
  removeBookmark: 'Видалити закладку',
  noBookmarks: 'Немає закладок',
  share: 'Поділитися',
  settings: 'Налаштування',
  theme: 'Тема',
  thumbnail: 'Мініатюра',
  language: 'Мова',
  animation: 'Анімація',
  category: {
    business: 'Бізнес',
    it: 'Ай Ті',
    military: 'Війна',
    news: 'Новини',
    science: 'Наука',
    softwareDevelopment: 'Ай Ті',
    space: 'Космос',
    technology: 'Технології',
  },
  noNews: 'Немає новин',
  genericError: 'Щось пішло не так. Спробуйте пізніше.',
  today: 'Сьогодні',
  yesterday: 'Вчора',
};

export default STR;
