#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Running linter"
  npm run lint;
  echo "Running tests"
  npm run test;
  echo "Running build"
  npm run build;
fi